language: python

services:
  - docker

before_install:
  - docker build -t debsahu/coronavirus .
  - docker run --rm debsahu/coronavirus

install: 
  - pip install -r requirements.txt

script:
  - python coronavirus.py